authserver:
    hostname: localhost
    port: 9031
    contextPath: uaa

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

ribbon:
  eureka:
    enabled: true

server:
  port: 9011

security:
  sessions: NEVER

spring:
  datasource:
    url: jdbc:mysql://localhost/iotdas?useSSL=false
    username: root
    password: root
    driver-class: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  # Note that the "/user" endpoint needs to provide the principle of the logged in user (/me endpoint)
